// <auto-generated />
using ArandukApp.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArandukApp.API.Migrations
{
    [DbContext(typeof(ArandukAppContext))]
    [Migration("20180815235349_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("ArandukApp.API.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autor");

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Titulo");

                    b.Property<string>("UrlAudio");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("ArandukApp.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreCastellano");

                    b.Property<string>("NombreGuarani");

                    b.Property<string>("UrlImagen");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ArandukApp.API.Models.Audio", b =>
                {
                    b.HasOne("ArandukApp.API.Models.Categoria")
                        .WithMany("Audios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
